[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 8000
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
